#!/bin/bash

# Rocky Linux bootstrap script for Minecraft server
# This script sets up a Minecraft server with systemd persistence
# Called remotely by: minectl deploy <user@host>

set -euo pipefail

# Defaults
PORT=25565
MEMORY="2G"
JAR_URL=""
SERVER_NAME=""
MC_BASE_DIR="/opt/minecraft"
MC_USER="minecraft"
JAVA_VERSION="17"

usage() {
    cat <<EOF
bootstrap.sh — Initialize Minecraft server on Rocky Linux

Usage:
  bootstrap.sh --server-name NAME [--port PORT] [--memory MEMORY] [--jar JAR_URL]

Options:
  --server-name NAME   Name of the server (required) — creates /opt/minecraft/NAME/
  --port PORT          Minecraft server port (default: 25565)
  --memory MEMORY      JVM memory allocation (default: 2G)
  --jar JAR_URL        Direct URL to server JAR (default: latest Vanilla)

EOF
    exit 1
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --server-name) SERVER_NAME="$2"; shift 2 ;;
        --port) PORT="$2"; shift 2 ;;
        --memory) MEMORY="$2"; shift 2 ;;
        --jar) JAR_URL="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

[[ -z "$SERVER_NAME" ]] && { echo "[bootstrap] ERROR: --server-name is required"; exit 1; }

log() {
    echo "[bootstrap] $1"
}

MC_HOME="$MC_BASE_DIR/servers/$SERVER_NAME"
SERVICE_NAME="minecraft-${SERVER_NAME}"

log "Starting Minecraft server bootstrap on Rocky Linux"
log "Server: $SERVER_NAME"
log "Server home: $MC_HOME"
log "Configuration: port=$PORT, memory=$MEMORY, jar_url=${JAR_URL:-vanilla}"

# Check if running as root (required for systemd setup)
if [[ $EUID -ne 0 ]]; then
    log "ERROR: This script must be run as root (via sudo)"
    exit 1
fi

# Step 1: Install Java
log "Installing Java $JAVA_VERSION..."
dnf install -y java-${JAVA_VERSION}-openjdk-headless

# Step 2: Create minecraft user and directories
log "Creating minecraft user and directories..."
if ! id "$MC_USER" &>/dev/null; then
    useradd -r -s /bin/bash "$MC_USER"
    log "Created user: $MC_USER"
fi

mkdir -p "$MC_HOME"
chown "$MC_USER:$MC_USER" "$MC_HOME"
chmod 755 "$MC_HOME"

cd "$MC_HOME"

# Create plugins and world directories
mkdir -p "$MC_HOME/plugins"
mkdir -p "$MC_HOME/world"
mkdir -p "$MC_HOME/.minectl"
chown -R "$MC_USER:$MC_USER" "$MC_HOME"

# Step 3: Download server JAR if not provided
if [[ -z "$JAR_URL" ]]; then
    log "Downloading Minecraft server JAR (vanilla)..."
    # Fetch the latest server JAR URL from launcher metadata
    LAUNCHER_META=$(curl -s https://launcher.mojang.com/v1/objects/index.json 2>/dev/null || echo "")
    JAR_URL=$(echo "$LAUNCHER_META" | grep -oP '"url": "\K[^"]*server\.jar' | head -1 2>/dev/null || echo "")
    
    if [[ -z "$JAR_URL" ]]; then
        log "WARNING: Could not auto-detect JAR URL. Using fallback."
        JAR_URL="https://launcher.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4116555cfa/server.jar"
    fi
fi

log "Downloading JAR from: $JAR_URL"
sudo -u "$MC_USER" curl -o "$MC_HOME/server.jar" -L "$JAR_URL"

# Step 4: Accept EULA
log "Creating eula.txt (accepting EULA)..."
sudo -u "$MC_USER" cat > "$MC_HOME/eula.txt" <<EOFEOF
# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).
# You also agree that tagging as an agent controlled by Microsoft/Mojang so we can identify bad agents.
# $(date)
eula=true
EOFEOF

# Step 5: Create server.properties
log "Creating server.properties..."
sudo -u "$MC_USER" cat > "$MC_HOME/server.properties" <<EOFEOF
# Minecraft server properties
# Generated by minectl bootstrap
# $(date)

server-port=$PORT
max-players=20
level-seed=
online-mode=true
enable-rcon=false
gamemode=survival
difficulty=normal
pvp=true
allow-flight=false
enable-command-block=false
max-world-size=29999984

EOFEOF

# Step 5b: Create per-server minectl config
log "Creating per-server minectl config..."
sudo -u "$MC_USER" cat > "$MC_HOME/.minectl/config.conf" <<EOFEOF
# minectl per-server configuration
# Generated: $(date)

ENABLED=true
PORT=$PORT
MEMORY=$MEMORY
JAR_PATH=$MC_HOME/server.jar

EOFEOF

# Step 6: Create systemd service
log "Installing systemd service: $SERVICE_NAME"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOFEOF
[Unit]
Description=Minecraft Server ($SERVER_NAME)
After=network.target

[Service]
Type=simple
User=$MC_USER
WorkingDirectory=$MC_HOME
ExecStart=/usr/bin/java -Xmx$MEMORY -Xms$MEMORY -jar $MC_HOME/server.jar nogui
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOFEOF

# Step 7: Enable systemd service
log "Enabling service for auto-start on boot..."
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"

# Step 8: Create server global config dir
mkdir -p "$MC_BASE_DIR/.minectl"
chown "$MC_USER:$MC_USER" "$MC_BASE_DIR/.minectl"

log "Bootstrap complete!"
log "Service installed: $SERVICE_NAME"
log "Server directory: $MC_HOME"
log "Server config: $MC_HOME/.minectl/config.conf"
log "To start: sudo systemctl start $SERVICE_NAME"
log "To check logs: sudo journalctl -u $SERVICE_NAME -f"
log "To manage: minectl start <user@host> --server-name $SERVER_NAME"
